# Generated by Django 5.1.3 on 2024-11-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default=None, max_length=50)),
                ('author_name', models.CharField(default=None, max_length=50)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(default=None, max_length=50)),
                ('stud_password', models.CharField(default='1234', max_length=50)),
                ('stud_phno', models.BigIntegerField(default=None)),
                ('stud_semester', models.IntegerField(default=None)),
                ('stud_image', models.ImageField(default=None, upload_to='stud_profile')),
                ('stud_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Issue_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.books')),
                ('stud_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.student')),
            ],
        ),
    ]
