# Generated by Django 5.1.3 on 2025-03-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_image',
            field=models.ImageField(default=None, upload_to='stud_profile/'),
        ),
    ]
